version: 2.1

jobs:
  build-and-test:
    machine:
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run:
          command: pyenv global 3.7.0
          name: Install dependencies
      - run:
          command: |
            python -m pip3 install pip_requirements.txt
            python3 -m pytest -s -v testcases/dex/test_dex_prv.py --no-print-logs -k DEX15
          name: Test DEX15

workflows:
  main:
    jobs:
      - build-and-test
