version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: pyenv global 3.7.0
          name: Install dependencies
      - run:
          command: pytest -s -v testcases/dex/test_dex_prv.py --no-print-logs -k DEX15
          name: Test DEX15

workflows:
  main:
    jobs:
      - build-and-test
