version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: pip3 install -r pip_requirements.txt
          name: Install dependencies
      - run:
          command: python3 -m pytest -s -v testcases/dex/test_dex_prv.py --no-print-logs -k DEX15
          name: Test DEX15

workflows:
  main:
    jobs:
      - build-and-test
